language: r
sudo: true
cache: packages
warnings_are_errors: false

# Environment variables for builds
env:
  global:
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
  - _R_CHECK_TIMINGS_="0"

# Avoid building vignettes
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

r:
  - release

# Code coverage
r_packages:
  - covr

# Report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
